language: java
jdk: oraclejdk8
install:
  - mvn install --settings .travis/settings.xml
deploy:
  - mvn clean deploy --settings .travis/settings.xml
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust